name: Practice-2
on: push
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
    - name: Get code
      uses: actions/checkout@v3
    - name: install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: test
        run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: Build code
        run: npm run build
      - name: deploy code
        run: echo "Deploying...."

          
      